# Generated by Django 2.1.4 on 2020-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_id', models.IntegerField()),
                ('Location', models.CharField(max_length=50)),
                ('StartTime_Shift1', models.CharField(max_length=50)),
                ('StartTime_Shift2', models.CharField(max_length=50)),
                ('StartTime_Shift3', models.CharField(max_length=50)),
            ],
        ),
    ]
